name: Build
 
on:
  workflow_dispatch:
    fork: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
 
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
 
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      
    - name: Build
      run: ./gradlew build
      
    - name: Output file tree to txt
      run: |
        cd /
        find . -type f > output/file-tree.txt
        
    - name: Archive file
      uses: actions/upload-artifact@v4
      with:
        name: end.txt
        path: output
